FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo pdo_pgsql pgsql

RUN a2enmod rewrite

COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . /app

RUN echo "DB_USER=${DB_USER}" > .env && \
    echo "DB_PASSWORD=${DB_PASSWORD}" >> .env && \
    echo "APP_URL=${APP_URL}" >> .env && \
    echo "dsn=${dsn}" >> .env

RUN chown -R www-data:www-data /app

EXPOSE 80
