FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_pgsql pgsql

RUN a2enmod rewrite

# Copie la configuration Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

WORKDIR /app

EXPOSE 80
