FROM php:8.3-apache

# Dépendances système
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo pdo_pgsql pgsql

# Modules Apache
RUN a2enmod rewrite

# Copier config Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . /app

RUN echo "DB_USER=${DB_USER}" > .env && \
    echo "DB_PASSWORD=${DB_PASSWORD}" >> .env && \
    echo "APP_URL=${APP_URL}" >> .env && \
    echo "dsn=${dsn}" >> .env

# Permissions
RUN chown -R www-data:www-data /app

EXPOSE 80
